# Form implementation generated from reading ui file 'bytton.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_circles(object):
    def setupUi(self, circles):
        circles.setObjectName("circles")
        circles.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=circles)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 440, 161, 61))
        self.pushButton.setObjectName("pushButton")
        circles.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=circles)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        circles.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=circles)
        self.statusbar.setObjectName("statusbar")
        circles.setStatusBar(self.statusbar)

        self.retranslateUi(circles)
        QtCore.QMetaObject.connectSlotsByName(circles)

    def retranslateUi(self, circles):
        _translate = QtCore.QCoreApplication.translate
        circles.setWindowTitle(_translate("circles", "MainWindow"))
        self.pushButton.setText(_translate("circles", "PushButton"))
